spring:
  application:
    name: hotel
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:./h2/database
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
